//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.11.30 at 01:12:43 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://medium.com/types/calculator", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package io.tbc.spring.ws.wsdlClasses;
